site_name: srt-core Documentation
site_url: https://srt-core.readthedocs.io/
repo_url: https://github.com/SolidRusT/srt-core
edit_uri: ""

nav:
  - Home: index.md
  - Configuration: config.md
  - Logger: logger.md

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  #analytics:
  #  gtag: G-ABC123

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SolidRusT/srt-core
